server:
  port: 7051
#  servlet:
#    context-path: /vrs
spring:
  profiles:
    active: dam
  application:
    name: vrs-venue
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /venue/v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vrs.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  level:
#    io.lettuce.core: DEBUG