server:
  port: 7060
#  servlet:
#    context-path: /aggregation
spring:
  profiles:
    active: dam
  application:
    name: vrs-aggregation
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /aggregation/v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vrs.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
aggregation:
  remote-url: http://127.0.0.1:${server.port}
logging:
  level:
    org.springframework.cloud.openfeign: debug