# 数据源集合
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/venue-reservation?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

rules:
  - !SHARDING
    tables:
      user:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.user_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: user_name
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
      time_period_model:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.time_period_model_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: partition_id
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
      time_period:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.time_period_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: partition_id
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
      venue_partition:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.venue_partition_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: venue_id
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
      time_period_order:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.time_period_order_${0..15}
        # 分表策略
        tableStrategy:
          # 复合分表策略（多个分片键）
          complex:
            # 用户 ID 和订单号
            shardingColumns: user_id,order_sn
            # 搜索 order_table_complex_mod 下方会有分表算法
            shardingAlgorithmName: order_table_gene_mod
      picture:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.picture_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: item_id
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
      time_period_pay:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.time_period_pay_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: order_sn
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: common_table_hash_mod
    # 分片算法
    shardingAlgorithms:
      # 数据表分片算法 使用的分片算法，根据数据的hashcode来进行取模（根据上面的配置知道是mod 16），值是多少就被分配到哪个表中
      common_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      # 订单分表算法
      order_table_gene_mod:
        # 通过加载全限定名类实现分片算法，相当于分片逻辑都在 algorithmClassName 对应的类中
        type: CLASS_BASED
        props:
          algorithmClassName: com.vrs.algorithm.OrderTableGeneAlgorithm
          # 分表数量
          sharding-count: 16
          # 复合（多分片键）分表策略
          strategy: complex
    # 展现逻辑 SQL & 真实 SQL
    # 逻辑SQL：select * from t_user where username = 'admin'
    # 真实SQL：select * from t_user_0 where username = 'admin'
  # 数据加密存储规则
  - !ENCRYPT
    # 需要加密的表集合
    tables:
      # 用户表
      user:
        # 用户表中哪些字段需要进行加密
        columns:
          # 手机号字段，逻辑字段，不一定是在数据库中真实存在
          phone_number:
            # 手机号字段存储的密文字段，这个是数据库中真实存在的字段
            cipherColumn: phone_number
            # 身份证字段加密算法
            encryptorName: common_encryptor
          email:
            cipherColumn: email
            encryptorName: common_encryptor
          password:
            cipherColumn: password
            encryptorName: common_encryptor
        # 是否按照密文字段查询
        queryWithCipherColumn: true
    # 加密算法
    encryptors:
      # 自定义加密算法名称
      common_encryptor:
        # 加密算法类型
        # AES 可逆
        type: AES
        props:
          # AES 加密密钥，密钥千万不能泄露，不然拿到数据就可以破解了
          aes-key-value: dadh423h343hg
props:
  sql-show: true